### ISSUE TITLE
asset mode and image in homepage

### ISSUE THREAD

**Issue by eephyne** [ppoffice/hexo-theme-hueman#1]
It seem that image aren't correctly displayed when the asset mode is active (meaning each post have his folder)
in the post the picture is /21/12/2004/boo.jpg but for the homepage (thumnails) it try to get /boo.jpg

Edit: after some digging its logical regarding the way img src is retrieved,
in article which is in /21/12/2004 the path to img is boo.jpg so when the script get it for the homepage he don't get the needed path.

so I assume it need a simple detection if asset mode is on to add the path of the article with the img src

**Comment by ppoffice** [comment]
Thumbnail image links are processed in themes\hueman\layout\_partial\post\thumbnail.ejs
```JavaScript
<a href="<%- url_for((post.link?post.link:post.path)) %>" class="thumbnail">
  <% if(theme.thumbnail == true) {
    var img=/\<img\s.*?\s?src\s*=\s*['|"]?([^\s'"]+).*?\>/ig;
    var result = post.content.match(img);
    var s = "";
    result = img.exec(post.content);
    if(result != null) {
      for(var i = result.length -1; i; --i){
          s += result[i]+"\n";
      }
    }
    if(s.length > 0){ %>
    <img src="<%= s %>" alt="<%= post.title %>" class="thumbnail-image" />
  <% } else { %>
    <span class="thumbnail-image thumbnail-none"></span>
  <% } %>
<% } else { %>
  <span class="thumbnail-image thumbnail-none"></span>
<% } %>
</a>
```
The program uses regular expression to find <img> tags in your rendered posts. This means you should use abosulte paths or relative paths begin with your root folder, such as `/hexo-theme-hueman/gallery/guitarist.jpg` of `http://ppoffice.github.io/hexo-theme-hueman/gallery/guitarist.jpg`.

An elegent way to solve this issue is to add a thumbnail detection plugin to your hexo blog, which I have thought about previously, but it's out of the range of this theme:)

**Comment by eephyne** [comment]
Shouldn't it be possible to detect asset setting and add path of post if path is relative? I can do it myself but I don't find how to get the config info,  config.post_asset_folder isn't working. I'm not familiar with hexo api and dev.

**Comment by ppoffice** [comment]
working on it

**Comment by ppoffice** [comment]
I made some changes to `themes\hueman\layout_partial\post\thumbnail.ejs`. Pull and see if your problems are solved.

**Comment by eephyne** [comment]
it work for homepage but not for categories for exemple, the link are still relative, it need to be transformed to absolute (simply prefix config.root should do it)

**Comment by ppoffice** [comment]
Thanks for help.

**Comment by eephyne** [comment]
my pleasure :)
